In [7]:
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
from sklearn import linear_model, preprocessing

In [8]:
# load data
data = pd.read_csv("car.data")
print(data.head(5))

  buying  maint door persons lug_boot safety  class
0  vhigh  vhigh    2       2    small    low  unacc
1  vhigh  vhigh    2       2    small    med  unacc
2  vhigh  vhigh    2       2    small   high  unacc
3  vhigh  vhigh    2       2      med    low  unacc
4  vhigh  vhigh    2       2      med    med  unacc


In [18]:
# preprocessing. code string values to numeric
le = preprocessing.LabelEncoder()
for var in ("buying", "maint", "lug_boot", "safety", "class", "door", "persons"):
    data[var] = le.fit_transform(list(data[var]))
predict = "class"
print(data.head(5))
print(type(data))

   buying  maint  door  persons  lug_boot  safety  class
0       3      3     0        0         2       1      2
1       3      3     0        0         2       2      2
2       3      3     0        0         2       0      2
3       3      3     0        0         1       1      2
4       3      3     0        0         1       2      2
<class 'pandas.core.frame.DataFrame'>


In [20]:
# split train test
X = np.array(data.drop([predict], 1))
y = np.array(data[predict])
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.1)
print(x_train, y_test)

[[2 3 0 2 0 1]
 [1 0 1 0 1 2]
 [3 2 0 1 0 0]
 ...
 [0 0 1 1 1 0]
 [1 1 1 1 2 0]
 [0 3 3 1 0 2]] [2 2 2 0 2 2 1 0 0 2 0 0 2 2 2 0 2 2 0 0 2 2 2 2 0 3 0 2 2 2 2 2 2 2 2 2 2
 0 0 2 2 2 2 0 2 2 0 0 2 3 0 3 0 2 0 2 2 2 2 2 2 0 2 2 2 1 2 2 0 2 2 2 2 2
 2 2 2 2 2 0 0 2 2 2 2 2 3 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 0 0 2 0 0
 2 2 1 0 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0
 2 2 2 2 2 2 0 0 2 2 0 2 3 2 2 2 2 2 2 2 2 3 0 2 2]


In [26]:
# model
model = KNeighborsClassifier(n_neighbors=9)
model.fit(x_train, y_train)
acc = model.score(x_test, y_test)
print(acc)

0.9248554913294798


In [32]:
# predict
predicted = model.predict(x_test)
names = ["unacc", "acc", "good", "vgood"]
for x in range(len(predicted)):
    print("Predicted: ", names[predicted[x]], "Data: ", x_test[x], "Actual: ", names[y_test[x]])
    n = model.kneighbors([x_test[x]], 9, True)
    print("N: ", n)







Predicted:  good Data:  [3 2 1 0 2 1] Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[ 645,   39, 1067,  857,  108, 1509,  939,  524,  549]]))
Predicted:  good Data:  [2 1 1 2 1 1] Actual:  good
N:  (array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]]), array([[ 252, 1280,  543, 1127, 1405, 1505,  500,  802,  283]]))
Predicted:  good Data:  [3 2 2 0 1 2] Actual:  good
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[1519, 1021, 1185,  750, 1434,  523, 1295, 1188,  538]]))
Predicted:  unacc Data:  [1 0 3 2 1 2] Actual:  unacc
N:  (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[ 173,  540, 1486,  867,  372, 1426,  433,  921,  875]]))
Predicted:  good Data:  [0 1 1 0 2 2] Actual:  good
N:  (array([[1.        , 1.   